apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosetta-ethereum-deploy
  labels:
    deploy: rosetta-ethereum-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rosetta-ethereum-pod
  template:
    metadata:
      labels:
        app: rosetta-ethereum-pod
      annotations:
        fluentd.active: "true"
    spec:
      containers:
        - name: rosetta-ethereum
          image: "ankrnetwork/rosetta-ethereum:feat"
          imagePullPolicy: IfNotPresent
          ports:
            - name: rest
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 10
          env:
            - name: MODE
              value: "ONLINE"
            - name: NETWORK
              value: "MAINNET"
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: rosetta-ethereum-svc
  labels:
    service: rosetta-ethereum-svc
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8080
      targetPort: rest
      protocol: TCP

  selector:
    app: rosetta-ethereum-pod
